"""Reader for the cerebro state JSON consumed by the dashboard.

Phase 2A: the state is a hand-curated mock at
`dashboard/data/cerebro_state.json` (gitignored — local-only because
it holds personal NAV / position data). When that file is absent (e.g.
fresh clone, first Streamlit Cloud deploy), the reader falls back to
`cerebro_state.example.json` which ships with the repo and renders a
demo state.

Phase 2B: replace the mock with a file generated by a daily cron that
invokes Anthropic API over snapshots + events + price log.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

DASHBOARD_DATA = Path(__file__).resolve().parents[1] / "data"
DEFAULT_STATE_PATH = DASHBOARD_DATA / "cerebro_state.json"
EXAMPLE_STATE_PATH = DASHBOARD_DATA / "cerebro_state.example.json"


def load_cerebro_state(path: Path | None = None) -> dict[str, Any]:
    if path is not None:
        with path.open("r", encoding="utf-8") as fp:
            return json.load(fp)
    if DEFAULT_STATE_PATH.exists():
        with DEFAULT_STATE_PATH.open("r", encoding="utf-8") as fp:
            return json.load(fp)
    with EXAMPLE_STATE_PATH.open("r", encoding="utf-8") as fp:
        return json.load(fp)
