"""End-to-end smoke for the dashboard surface.

Each test is intentionally cheap and side-effect-free:
- AST-parses every dashboard page module so a syntax slip would fail
  before the user ever opens Streamlit.
- AST-parses every dashboard service.
- Verifies the cerebro state JSON loads and carries the keys the pages
  consume.
- Verifies at least one real-portfolio snapshot exists.
"""

from __future__ import annotations

import ast
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PAGES_DIR = ROOT / "dashboard" / "pages"
SERVICES_DIR = ROOT / "dashboard" / "services"
CEREBRO_PATH = ROOT / "dashboard" / "data" / "cerebro_state.json"
SNAPSHOT_DIR = ROOT / "data" / "snapshots" / "real"


def _ast_parse(p: Path) -> None:
    src = p.read_text(encoding="utf-8")
    ast.parse(src, filename=str(p))


# ---------------------------------------------------------------------------
class TestPageModules:
    def test_at_least_eight_pages_present(self):
        pages = sorted(PAGES_DIR.glob("*_*.py"))
        assert len(pages) >= 8, (
            f"Expected ≥8 dashboard pages, found {len(pages)}: "
            f"{[p.name for p in pages]}"
        )

    def test_every_page_module_parses(self):
        pages = sorted(PAGES_DIR.glob("*_*.py"))
        failures: list[tuple[str, str]] = []
        for p in pages:
            try:
                _ast_parse(p)
            except SyntaxError as exc:
                failures.append((p.name, str(exc)))
        assert not failures, "Syntax errors: " + "; ".join(
            f"{n}: {e}" for n, e in failures
        )


# ---------------------------------------------------------------------------
class TestServiceModules:
    def test_every_service_parses(self):
        if not SERVICES_DIR.exists():
            pytest.skip("dashboard/services not present")
        modules = [
            p for p in SERVICES_DIR.glob("*.py") if p.name != "__init__.py"
        ]
        assert modules, "No service modules found"
        failures: list[tuple[str, str]] = []
        for p in modules:
            try:
                _ast_parse(p)
            except SyntaxError as exc:
                failures.append((p.name, str(exc)))
        assert not failures, "Syntax errors: " + "; ".join(
            f"{n}: {e}" for n, e in failures
        )


# ---------------------------------------------------------------------------
class TestCerebroState:
    def test_cerebro_state_loads(self):
        if not CEREBRO_PATH.exists():
            pytest.skip(
                "cerebro_state.json not present — generated by the daily "
                "cron or via 'Iniciar evaluación' in the sidebar"
            )
        state = json.loads(CEREBRO_PATH.read_text(encoding="utf-8"))
        # Keys the pages actually consume in this build:
        for key in (
            "as_of_date",
            "portfolio_real",
            "recommendations",
            "news_by_asset",
            "technicals_by_asset",
            "fundamentals_by_asset",
            "debates_by_asset",
            "brier_score_30d",
        ):
            assert key in state, f"cerebro_state missing key: {key}"


# ---------------------------------------------------------------------------
class TestSnapshotPresence:
    def test_snapshot_real_exists(self):
        if not SNAPSHOT_DIR.exists():
            pytest.skip("data/snapshots/real not present")
        snaps = list(SNAPSHOT_DIR.glob("*.json"))
        assert snaps, "Expected at least one real-portfolio snapshot"
